DROP TABLE IF EXISTS OFFER_TEXT;
DROP TABLE IF EXISTS OFFER;
DROP TABLE IF EXISTS PRODUCT_IMAGE;
DROP TABLE IF EXISTS PRODUCT_PRICE;
DROP TABLE IF EXISTS PRODUCT_CATEGORY;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CATEGORY;