DELETE FROM CATEGORY;
INSERT INTO CATEGORY(ID, NAME, BACKGROUND_IMAGE) VALUES(1, 'Blusas para fêmeas', '/drawable/product_ref11_ref12');
INSERT INTO CATEGORY(ID, NAME, BACKGROUND_IMAGE) VALUES(2, 'Blusas para machos', '/drawable/product_ref9_ref10');
INSERT INTO CATEGORY(ID, NAME, BACKGROUND_IMAGE) VALUES(3, 'Blusas unissex', '/drawable/product_ref27');
INSERT INTO CATEGORY(ID, NAME, BACKGROUND_IMAGE) VALUES(4, 'Calcinhas', '/drawable/product_ref2_ref2a');
INSERT INTO CATEGORY(ID, NAME, BACKGROUND_IMAGE) VALUES(5, 'Capas para fêmeas', '/drawable/product_ref50');
INSERT INTO CATEGORY(ID, NAME, BACKGROUND_IMAGE) VALUES(6, 'Capas para machos', '/drawable/product_ref51');
INSERT INTO CATEGORY(ID, NAME, BACKGROUND_IMAGE) VALUES(7, 'Coletes para fêmeas', null);
INSERT INTO CATEGORY(ID, NAME, BACKGROUND_IMAGE) VALUES(8, 'Coletes para machos', '/drawable/product_ref30_ref31_1');
INSERT INTO CATEGORY(ID, NAME, BACKGROUND_IMAGE) VALUES(9, 'Fêmeas', '/drawable/product_ref59');
INSERT INTO CATEGORY(ID, NAME, BACKGROUND_IMAGE) VALUES(10, 'Jaquetas para fêmea', '/drawable/product_ref32');
INSERT INTO CATEGORY(ID, NAME, BACKGROUND_IMAGE) VALUES(11, 'Jaquetas para machos', '/drawable/product_ref33');
INSERT INTO CATEGORY(ID, NAME, BACKGROUND_IMAGE) VALUES(12, 'Jaquetas unissex', '/drawable/product_ref37');
INSERT INTO CATEGORY(ID, NAME, BACKGROUND_IMAGE) VALUES(13, 'Macacões fêmeas', '/drawable/product_ref41_ref42');
INSERT INTO CATEGORY(ID, NAME, BACKGROUND_IMAGE) VALUES(14, 'Macacões machos', '/drawable/product_ref41_ref42');
INSERT INTO CATEGORY(ID, NAME, BACKGROUND_IMAGE) VALUES(15, 'Machos', '/drawable/product_ref55_ref56_ref57_ref58');
INSERT INTO CATEGORY(ID, NAME, BACKGROUND_IMAGE) VALUES(16, 'Personagens', '/drawable/product_ref43');
INSERT INTO CATEGORY(ID, NAME, BACKGROUND_IMAGE) VALUES(17, 'Unissex', '/drawable/product_ref52');
INSERT INTO CATEGORY(ID, NAME, BACKGROUND_IMAGE) VALUES(18, 'Vestidos', '/drawable/product_ref1');