DELETE FROM PRODUCT;
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (1, '1', 'Vestido Minnie Classic', 'Tecido: Plush importado com elastano, Aplique Glitter em material importado de alta resistência e durabilidade. Acabamento em ribana, laço de cetim, renda Jabó.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (2, '2', 'Vestido Baby Nuvens', 'Tecido: Microsoft, apliques de ursinho e laço, tira de renda com pérolas na cintura, fita de pompom griló na barra. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (3, '2A', 'Calcinha Vestido Baby Nuvens', 'Tecido: Microsoft, Renda Jabô, aplique de ursinho, fechamento com botão de pressão.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (4, '3', 'Vestido Bolinha', 'Tecido: Microsoft, apliques de urso e laço. Acabamento em ribana, fita pompom griló.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (5, '4', 'Vestido Charmosinha', 'Tecido: Soft Ski Jacquard, soft ski exportação apliques de gatinha e flores. Acabamento em ribana e renda Jabô.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (6, '5', 'Vestido Glamour', 'Tecido: Pelúcia, plush com elastano, apliques de gatinha e flores. Acabamento em ribana, fita de pompom griló, e renda Jabô');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (7, '5A', 'Calcinha Vestido Glamour', 'Tecido: Pelúcia, apliques de Laço, fechamento com botão de pressão.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (8, '6', 'Vestido Ovelhinha Feliz', 'Tecido: Pelúcia, plush, aplique bordado a máquina, lacinho. Acabamento em ribana, fita de pompom griló e renda Jabô');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (9, '6A', 'Calcinha Vestido Ovelhinha Feliz', 'Tecido: Pelucia, fechamento com botão de pressão.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (10, '7', 'Vestido Ursinho', 'Tecido: Soft Ski Jacquard, plush, apliques de ursinho e flores. Acabamento em ribana, fita de pompom griló, e renda Jabô.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (11, '7A', 'Calcinha Vestido Ursinho', 'Tecido: Soft Ski, renda Jabô, aplique de ursinho e laço, fechamento em botão de pressão.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (12, '7B', 'Calcinha Vestido Ursinho', 'Tecido: Soft Ski, aplique de ursinho e laço, fechamento em botão de pressão.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (13, '8', 'Vestido Kitty', 'Tecido: Microsoft liso e estampado, aplique com glitter, lacinho. Acabamento em ribana, fita de pompom griló e renda Jabô.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (14, '9', 'Blusa Ursinho Blue', 'Tecido: Pelúcia aplique 3D bordado a máquina. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (15, '10', 'Blusa Ursinho Black', 'Tecido: Pelúcia aplique 3D bordado a máquina. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (16, '11', 'Blusa Ursinha Rosa', 'Tecido: Pelúcia aplique 3D bordado a máquina. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (17, '12', 'Blusa Ursinha Red', 'Tecido: Pelúcia aplique 3D bordado a máquina. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (18, '13', 'Blusa Gatinha', 'Tecido: Plush, aplique 3D bordado a máquina. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (19, '14', 'Blusa Gatinho', 'Tecido: Plush, aplique 3D bordado a máquina. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (20, '15', 'Blusa Cachorrinha', 'Tecido: Soft Glacê rosa, Plush com elastano marrom, aplique 3D bordado a máquina, lacinho. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (21, '16', 'Blusa Cachorrinho', 'Tecido: Soft Glacê rosa, Plush com elastano marrom, aplique 3D bordado a máquina, lacinho. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (22, '17', 'Blusa Ovelhinha Boy', 'Tecido: Plush, aplique 3D bordado a máquina, lacinho. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (23, '18', 'Blusa Ovelhinha Girl', 'Tecido: Plush, aplique 3D bordado a máquina, lacinho. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (24, '19', 'Blusa Docinho Boy', 'Tecido: Plush com elastano, apliques de ursinho e laço. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (25, '20', 'Blusa Docinho Girl', 'Tecido: Plush com elastano, apliques de ursinho e laço. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (26, '21', 'Blusa Unicórnio Azul', 'Tecido: Microsoft aplique em Glitter, flores Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (27, '22', 'Blusa Unicórnio Rosa', 'Tecido: Microsoft aplique em Glitter, flores Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (28, '23', 'Blusa Eu amo Ossinhos', 'Tecido: Soft Glacê, apliques em filme de recorte de alta resistência. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (29, '24', 'Blusa Eu amo Petiscos', 'Tecido: Soft Glacê, apliques em filme de recorte de alta resistência. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (30, '25', 'Blusa Angel Rosa', 'Tecido: Soft Glacê rosa, Tweed preto, aplique em Glitter branco e pink, Acabamento em ribana');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (31, '26', 'Blusa Angel Black', 'Tecido: Soft Glacê rosa, Tweed preto, aplique em Glitter branco e pink, Acabamento em ribana');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (32, '27', 'Blusa Chihuahua Relax', 'Tecido: Plush, apliques em filme de recorte de alta resistência. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (33, '28', 'Blusa Cat Girl', 'Tecido: Plush, aplique com filme Glitter, Acabamento em ribana e laço.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (34, '29', 'Blusa Princess', 'Tecido: Plush, aplique com filme Glitter, Acabamento em ribana e laço.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (35, '30', 'Jaqueta Mickey Love', 'Tecido: Moletom, aplique em filme de recorte de alta resistência. Capuz forrado com malha, orelhas em 3D Acabamento em ribana, ziper.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (36, '31', 'Colete Mickey Belezinha AZUL', 'Tecido: Plush com elastano, aplique com filme Glitter, Com capuz forrado em malha. Acabamento em ribana e zíper.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (37, '32', 'Jaqueta Minnie Classic', 'Tecido: Plush com elastano, aplique em filme de recorte Glitter de alta resistência. Capuz forrado com malha, aplique. Acabamento em ribana, ziper.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (38, '33', 'Jaqueta He Ho', 'Tecido: Moletom, aplique em filme de recorte de alta resistência. Capuz forrado com malha, Acabamento em ribana, ziper.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (39, '34', 'Jaqueta Pet Love', 'Tecido: Moletom, aplique em filme de recorte de alta resistência. Capuz forrado com malha, Acabamento em ribana, ziper.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (40, '35', 'Blusa Ursinho Gravata Azu', 'Tecido: Soft Ski Jacquard, apliques de ursinho e laço, com e sem capuz (forrado com pele carneirinho). Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (41, '36', 'Blusa Ursinho Laço', 'Tecido: Soft Ski Jacquard, apliques de ursinho e laço, com e sem capuz (forrado com pele carneirinho). Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (42, '37', 'Blusa Mickey Glitter', 'Tecido: Tweed, aplique em Glitter. Acabamento em ribana, capuz forrado em malha com orelhas 3D.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (43, '38', 'Blusa Nuvenzinha Boy', 'Tecido: Microsoft, aplique bordado nas costas, laço. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (44, '39', 'Blusa Coraçãozinho', 'Tecido: Microsoft, aplique bordado nas costas, laço. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (45, '40', 'Blusa Nuvenzinha Girl', 'Tecido: Microsoft, aplique bordado nas costas, laço. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (46, '41', 'Macacão Boy', 'Tecido: Microsoft e Plush, acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (47, '42', 'Macacão Girl', 'Tecido: Microsoft e Plush, acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (48, '43', 'Blusa Stitch', 'Tecido: Plush, aplique bordado nas costas, capuz 3D bordado a máquina. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (49, '44', 'Blusa Capitão América', 'Tecido: Soft Ski, aplique bordado nas costas. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (50, '45', 'Blusa Burro', 'Tecido: Plush, capuz 3D bordado a máquina. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (51, '46', 'Blusa Tigrão', 'Tecido: Plush, capuz 3D bordado a máquina. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (52, '47', 'Blusa Leitão', 'Tecido: Plush, aplique bordado nas costas, capuz 3D bordado a máquina. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (53, '48', 'Blusa Ursinho Pooh', 'Tecido: Plush, aplique bordado nas costas, capuz 3D bordado a máquina. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (54, '49N', 'Blusa Ursinho Carinhosos Nuvem', 'Tecido: Plush, aplique bordado nas costas, capuz 3D bordado a máquina. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (55, '49Z', 'Blusa Ursinho Carinhosos Zangado', 'Tecido: Plush, aplique bordado nas costas, capuz 3D bordado a máquina. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (56, '49P', 'Blusa Ursinho Carinhosos Pirulito', 'Tecido: Plush, aplique bordado nas costas, capuz 3D bordado a máquina. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (57, '49A', 'Blusa Ursinho Carinhosos Arco Iris', 'Tecido: Plush, aplique bordado nas costas, capuz 3D bordado a máquina. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (58, '49S', 'Blusa Ursinho Carinhosos Sol', 'Tecido: Plush, aplique bordado nas costas, capuz 3D bordado a máquina. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (59, '49C', 'Blusa Ursinho Carinhosos Coração', 'Tecido: Plush, aplique bordado nas costas, capuz 3D bordado a máquina. Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (60, '50', 'Capa Style Girl', 'Tecido: Matelassê, pelúcia. Acabamento com botão de pressão.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (61, '51', 'Capa Style Boy', 'Tecido: Matelassê, pelúcia. Acabamento com botão de pressão.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (62, '52RAM', 'Camisa Rock Ramones', 'Tecido: Plush, aplique em filme de recorte, resistente e durável Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (63, '52LEG', 'Camisa Rock LEGIÃO URBANA', 'Tecido: Plush, aplique em filme de recorte, resistente e durável Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (64, '52RAU', 'Camisa Rock RAUL', 'Tecido: Plush, aplique em filme de recorte, resistente e durável Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (65, '52LED', 'Camisa Rock LED ZEPPELIN', 'Tecido: Plush, aplique em filme de recorte, resistente e durável Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (66, '52ROC', 'Camisa Rock ROCK ROLL', 'Tecido: Plush, aplique em filme de recorte, resistente e durável Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (67, '52MET', 'Camisa Rock METALLICA', 'Tecido: Plush, aplique em filme de recorte, resistente e durável Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (68, '52KIS', 'Camisa Rock KISS', 'Tecido: Plush, aplique em filme de recorte, resistente e durável Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (69, '52RED', 'Camisa Rock RED HOT CHILLI PEPPERS', 'Tecido: Plush, aplique em filme de recorte, resistente e durável Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (70, '52ROL', 'Camisa Rock ROLLING STONES', 'Tecido: Plush, aplique em filme de recorte, resistente e durável Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (71, '52ELV', 'Camisa Rock ELVIS PRESLEY', 'Tecido: Plush, aplique em filme de recorte, resistente e durável Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (72, '52DOO', 'Camisa Rock DOORS', 'Tecido: Plush, aplique em filme de recorte, resistente e durável Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (73, '52GUN', 'Camisa Rock GUNS', 'Tecido: Plush, aplique em filme de recorte, resistente e durável Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (74, '52IRO', 'Camisa Rock IRON MAIDEN', 'Tecido: Plush, aplique em filme de recorte, resistente e durável Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (75, '52NAZ', 'Camisa Rock NAZARETH', 'Tecido: Plush, aplique em filme de recorte, resistente e durável Acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (76, '53', 'Calça Hora do passeio', 'Tecido: Moletom, aplique em filme de recorte de alta resistência e durabilidade, acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (77, '54', 'Calça Hora do passeio', 'Tecido: Moletom, aplique em filme de recorte de alta resistência e durabilidade, acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (78, '55', 'Calça Hora do passeio', 'Tecido: Moletom, aplique em filme de recorte de alta resistência e durabilidade, acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (79, '56', 'Calça Hora do passeio', 'Tecido: Moletom, aplique em filme de recorte de alta resistência e durabilidade, acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (80, '57', 'Calça Hora do passeio', 'Tecido: Moletom, aplique em filme de recorte de alta resistência e durabilidade, acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (81, '58', 'Calça Hora do passeio', 'Tecido: Moletom, aplique em filme de recorte de alta resistência e durabilidade, acabamento em ribana.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (82, '59', 'Vestido Caipira', 'Tecido: Tricoline pink e floral, renda Jabô e lacinhos de cetim. Fechamento com botão de pressão de plástico.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (83, '60', 'Vestido Caipira', 'Tecido: Tricoline pink e floral, renda Jabô e lacinhos de cetim. Fechamento com botão de pressão de plástico.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (84, '61', 'Vestido Caipira', 'Tecido: Tricoline pink e floral, renda Jabô e lacinhos de cetim. Fechamento com botão de pressão de plástico.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (85, '62', 'Vestido Caipira', 'Tecido: Tricoline pink e floral, renda Jabô e lacinhos de cetim. Fechamento com botão de pressão de plástico.');
INSERT INTO PRODUCT(ID, REFERENCE_CODE, NAME, DESCRIPTION) VALUES (86, '63', 'Vestido Caipira', 'Tecido: Tricoline pink e floral, renda Jabô e lacinhos de cetim. Fechamento com botão de pressão de plástico.');